services:

  # ---------------------------------------------------------------------------
  # REVERSE PROXY
  # ---------------------------------------------------------------------------
  reverse-proxy:
    image: nginx:1.27-alpine
    container_name: reverse-proxy
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - snippet
      - formatter
      - linter
      - tester
      - authentication
      - permission
      - engine
      - ui                      
    networks:
      - snippet-net
    restart: unless-stopped

  # ---------------------------------------------------------------------------
  # GLOBAL SERVICES
  # ---------------------------------------------------------------------------

  redis:
    image: redis:6-alpine
    container_name: redis
    env_file:
      - env/redis/.env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - snippet-net

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace
    networks:
      - snippet-net

  asset-service:
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    container_name: asset-service
    environment:
      NEW_RELIC_AGENT_ENABLED: "true"
    env_file:
      - env/asset/.env
    depends_on:
      azurite:
        condition: service_started
    networks:
      - snippet-net
    restart: unless-stopped

  # ---------------------------------------------------------------------------
  # SNIPPET SERVICE
  # ---------------------------------------------------------------------------

  snippet-db:
    image: postgres:alpine
    env_file:
      - env/snippet/.env
    volumes:
      - snippet-db:/var/lib/postgresql/data
    networks:
      - snippet-net
    restart: unless-stopped

  snippet:
    image: ghcr.io/ingsisprintscript/snippet-service:dev
    container_name: snippet-service
    env_file:
      - env/snippet/.env
    depends_on:
      redis:
        condition: service_healthy
      snippet-db:
        condition: service_started
      asset-service:
        condition: service_started
    networks:
      - snippet-net
    restart: unless-stopped
  # ---------------------------------------------------------------------------
  # FORMAT SERVICE
  # --------------------------------------------------------------------------

  format-db:
    image: postgres:alpine
    env_file:
      - env/format/.env
    volumes:
      - format-db:/var/lib/postgresql/data
    networks:
      - snippet-net
    restart: unless-stopped

  formatter:
    image: ghcr.io/ingsisprintscript/format-service:dev
    container_name: formatter
    env_file:
      - env/format/.env
    depends_on:
      redis:
        condition: service_healthy
      format-db:
        condition: service_started
      asset-service:
        condition: service_started
    networks:
      - snippet-net
    restart: unless-stopped

  # ---------------------------------------------------------------------------
  # LINTER SERVICE
  # ---------------------------------------------------------------------------

  linter-db:
    image: postgres:alpine
    env_file:
      - env/linter/.env
    volumes:
      - linter-db:/var/lib/postgresql/data
    networks:
      - snippet-net
    restart: unless-stopped

  linter:
    image: ghcr.io/ingsisprintscript/linter-service:dev
    container_name: linter-service
    env_file:
      - env/linter/.env
    depends_on:
      redis:
        condition: service_healthy
      linter-db:
        condition: service_started
      asset-service:
        condition: service_started
    networks:
      - snippet-net
    restart: unless-stopped

  # ---------------------------------------------------------------------------
  # TEST SERVICE
  # ---------------------------------------------------------------------------

  test-db:
    image: postgres:alpine
    env_file:
      - env/test/.env
    volumes:
      - test-db:/var/lib/postgresql/data
    networks:
      - snippet-net
    restart: unless-stopped

  tester:
    image: ghcr.io/ingsisprintscript/test-service:dev
    container_name: tester
    env_file:
      - env/test/.env
    depends_on:
      redis:
        condition: service_healthy
      test-db:
        condition: service_started
      asset-service:
        condition: service_started
    networks:
      - snippet-net
    restart: unless-stopped

  # ---------------------------------------------------------------------------
  # AUTH SERVICE
  # ---------------------------------------------------------------------------

  authentication-db:
    image: postgres:alpine
    env_file:
      - env/authentication/.env
    volumes:
      - authentication-db:/var/lib/postgresql/data
    networks:
      - snippet-net
    restart: unless-stopped

  authentication:
    image: ghcr.io/ingsisprintscript/users-authorization:dev
    container_name: authentication-service
    env_file:
      - env/authentication/.env
    depends_on:
      authentication-db:
        condition: service_started
    networks:
      - snippet-net
    restart: unless-stopped

  # ---------------------------------------------------------------------------
  # PERMISSION SERVICE
  # ---------------------------------------------------------------------------

  permission-db:
    image: postgres:alpine
    env_file:
      - env/permission/.env
    volumes:
      - permission-db:/var/lib/postgresql/data
    networks:
      - snippet-net
    restart: unless-stopped

  permission:
    image: ghcr.io/ingsisprintscript/permission-service:dev
    container_name: permission-service
    env_file:
      - env/permission/.env
    depends_on:
      permission-db:
        condition: service_started
    networks:
      - snippet-net
    restart: unless-stopped

  # ---------------------------------------------------------------------------
  # ENGINE SERVICE (NUEVO)
  # ---------------------------------------------------------------------------

  engine:
    image: ghcr.io/ingsisprintscript/engine-service:dev
    container_name: engine-service
    env_file:
      - env/engine/.env
    networks:
      - snippet-net
    restart: unless-stopped

  # ---------------------------------------------------------------------------
  # UI SERVICE (NUEVO)
  # ---------------------------------------------------------------------------
  ui:
    build:
      context: ../printscript-ui
      dockerfile: Dockerfile
    env_file:
      - env/ui/.env
    container_name: ui
    networks:
      - snippet-net
    restart: unless-stopped

# ---------------------------------------------------------------------------
# VOLUMES
# ---------------------------------------------------------------------------
volumes:
  snippet-db:
  format-db:
  linter-db:
  test-db:
  authentication-db:
  permission-db:
  redis-data:
  blob:

# ---------------------------------------------------------------------------
# NETWORKS
# ---------------------------------------------------------------------------
networks:
  snippet-net:
    driver: bridge
