# Redirección de HTTP a HTTPS
server {
    listen 80;
    server_name snippet-dev.duckdns.org;
    return 301 https://$host$request_uri;
}

# Servidor HTTPS
server {
    listen 443 ssl;
    server_name snippet-dev.duckdns.org;

    ssl_certificate     /etc/letsencrypt/live/snippet-dev.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/snippet-dev.duckdns.org/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # -------------------------
    # FRONTEND
    # -------------------------
    location / {
        proxy_pass http://ui:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # -------------------------
    # SNIPPET-SERVICE (API PRINCIPAL)
    # -------------------------
    location /snippet/ {
        proxy_pass http://snippet:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # -------------------------
    # ENGINE SERVICE
    # -------------------------
    location /engine/ {
        proxy_pass http://engine:8089/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # -------------------------
    # FORMAT SERVICE
    # -------------------------
    location /format/ {
        proxy_pass http://formatter:8082/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # -------------------------
    # LINT SERVICE
    # -------------------------
    location /lint/ {
        proxy_pass http://linter:8085/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # -------------------------
    # TEST SNIPPET SERVICE
    # -------------------------
    location /test-snippet/ {
        proxy_pass http://tester:8086/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # -------------------------
    # AUTH SERVICE
    # -------------------------
    location /auth/ {
        proxy_pass http://authentication:8087/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # -------------------------
    # PERMISSION SERVICE
    # -------------------------
    location /permission/ {
        proxy_pass http://permission:8088/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
