server {
    listen 80;
    server_name snippet-dev.duckdns.org;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name snippet-dev.duckdns.org;

    ssl_certificate     /etc/letsencrypt/live/snippet-dev.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/snippet-dev.duckdns.org/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    # 🔹 DNS interno de Docker (OBLIGATORIO)
    resolver 127.0.0.11 valid=10s;

    location /snippet-service/ {
        proxy_pass http://snippet-service:8081/;
        include /etc/nginx/proxy_params;
    }

    location /auth/ {
        proxy_pass http://authentication-service:8085/;
        include /etc/nginx/proxy_params;
    }

    location /permission/ {
        proxy_pass http://permission-service:8086/;
        include /etc/nginx/proxy_params;
    }

    location /engine/ {
        proxy_pass http://engine-service:8088/;
        include /etc/nginx/proxy_params;
    }

    location / {
        proxy_pass http://ui:80;
        include /etc/nginx/proxy_params;
    }
}